"""Top-level package for CoTeDe.

This file exposes the most commonly used classes and subpackages so the
package is convenient to use via `import cotede`.
"""

from importlib import import_module
from typing import Any

# Public subpackages/modules
from . import datasets, qctests, fuzzy, anomaly_detection, utils
from .misc import combined_flag, make_qc_index

# Core classes
from .qc import ProfileQC, ProfileQCed

# Version: prefer setuptools_scm generated file if present, otherwise fall
# back to a simple default. setuptools_scm can write a `cotede/version.py`
# during build which will define a `version` variable.
try:
	# generated by setuptools_scm when building a distribution
	from .version import version as __version__  # type: ignore
except Exception:
	__version__ = "0.1.0"

__all__ = [
	"ProfileQC",
	"ProfileQCed",
	"datasets",
	"qctests",
	"fuzzy",
	"anomaly_detection",
	"utils",
	"combined_flag",
	"make_qc_index",
	"__version__",
]

